log_level = "warn"
position = "Top"
app_launcher_cmd = "fuzzel"

[modules]
left = [ [ "appLauncher", "Updates", "Workspaces", "Tray" ] ]
center = [ "WindowTitle" ]
right = [ "SystemInfo", [  "Clock", "calendar", "Privacy", "Settings" ] ]

[updates]
check_cmd = "checkupdates; paru -Qua"
update_cmd = 'alacritty -e bash -c "paru; echo Done - Press enter to exit; read" &'

[workspaces]
enable_workspace_filling = true

[[CustomModule]]
name = "appLauncher"
icon = "󱗼"
command = "fuzzel"

[[CustomModule]]
name = "calendar"
icon = " "
command = "zenity --calendar --title=\"Calendar\""

[window_title]
truncate_title_after_length = 100

[settings]
lock_cmd = "playerctl --all-players pause; hyprlock &"
shutdown_cmd = "shutdown now"
suspend_cmd = "systemctl suspend"
reboot_cmd = "systemctl reboot"
logout_cmd = "loginctl kill-user $(whoami)"
audio_sinks_more_cmd = "pavucontrol -t 3"
audio_sources_more_cmd = "pavucontrol -t 4"
wifi_more_cmd = "nm-connection-editor"
vpn_more_cmd = "nm-connection-editor"
bluetooth_more_cmd = "blueberry"

[appearance]
scale_factor = 1.1
style = "Solid"
opacity = 0.5

primary_color = "#7aa2f7"
success_color = "#9ece6a"
text_color = "#dddddd"

workspace_colors = [ "#7aa2f7" ]

[appearance.danger_color]
base = "#f7768e"
weak = "#e0af68"

[appearance.background_color]
base = "#1a1b26"
weak = "#24273a"
strong = "#414868"

[appearance.secondary_color]
base = "#0c0d14"
